import jsPDF from 'jspdf';

interface ExportOptions {
  title: string;
  connectionName: string;
  charts: { title: string; chartImage: string; rowCount?: number; sql?: string | null }[];
  date: string;
}

/**
 * Export dashboard as a branded PDF with title page and chart sections.
 */
export async function exportDashboardPdf(options: ExportOptions): Promise<void> {
  const { title, connectionName, charts, date } = options;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  // Title page
  doc.setFillColor(13, 13, 14);
  doc.rect(0, 0, pageW, pageH, 'F');

  // Accent bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 4, pageH, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(32);
  doc.text(title, 20, pageH * 0.35);

  doc.setFontSize(14);
  doc.setTextColor(156, 163, 175);
  doc.text(connectionName, 20, pageH * 0.35 + 14);
  doc.text(date, 20, pageH * 0.35 + 24);

  doc.setFontSize(11);
  doc.setTextColor(107, 114, 128);
  doc.text(`${charts.length} chart${charts.length !== 1 ? 's' : ''}`, 20, pageH * 0.35 + 38);

  // Footer on title page
  doc.setFontSize(9);
  doc.setTextColor(75, 85, 99);
  doc.text('Generated by Data Explorer', 20, pageH - 15);

  // Chart pages
  for (let i = 0; i < charts.length; i++) {
    const chart = charts[i];
    doc.addPage();

    // Header bar
    doc.setFillColor(17, 18, 19);
    doc.rect(0, 0, pageW, 18, 'F');
    doc.setFillColor(99, 102, 241);
    doc.rect(0, 0, 4, 18, 'F');

    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text(chart.title, 12, 12);

    doc.setFontSize(9);
    doc.setTextColor(156, 163, 175);
    doc.text(`${i + 1} / ${charts.length}`, pageW - 20, 12);

    // Chart image
    const imgY = 24;
    const imgW = pageW - 24;
    const imgH = pageH - 60;
    try {
      doc.addImage(chart.chartImage, 'PNG', 12, imgY, imgW, imgH);
    } catch {
      doc.setFontSize(11);
      doc.setTextColor(156, 163, 175);
      doc.text('Chart image could not be rendered', pageW / 2, imgY + imgH / 2, { align: 'center' });
    }

    // Footer with metadata
    const footerY = pageH - 12;
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    if (chart.rowCount) {
      doc.text(`${chart.rowCount.toLocaleString()} rows`, 12, footerY);
    }
    if (chart.sql) {
      const sqlPreview = chart.sql.length > 100 ? chart.sql.slice(0, 100) + '...' : chart.sql;
      doc.text(sqlPreview, 12, footerY + 5);
    }
  }

  doc.save(`${title.replace(/[^a-zA-Z0-9\s-]/g, '').trim()}.pdf`);
}
